Repository kvassAI/order-widget, pull requests merged in 2018-07, with the labels that each got.

#72 Fix powered by
  src/components/Footer/index.scss
  src/utils/i18n.js
Labels: bug, review, waiting for review

#79 Add Order ID in receipt
  src/containers/ConfirmOrder/index.jsx
  src/containers/Receipt/index.jsx
  src/reflux/Actions.js
  src/reflux/GlobalStore.js
  src/reflux/OrderStore.js
  src/utils/i18n.js
Labels: review, waiting for review

#82 Dynamic heights
  package-lock.json
  src/components/Footer/index.scss
  src/components/ProductList/index.jsx
  src/components/Spinner/index.scss
  src/containers/ConfirmOrder/index.scss
  src/containers/DeliveryDetails/index.scss
  src/containers/PaymentDetails/index.scss
  src/containers/ProductBasket/index.jsx
  src/containers/ProductBasket/index.scss
  src/containers/ProductPage/index.jsx
  src/containers/ProductPage/index.scss
  src/containers/ProductSearch/index.scss
  src/containers/Receipt/index.jsx
  src/containers/Receipt/index.scss
  src/containers/UserDetails/index.jsx
  src/containers/UserDetails/index.scss
  src/styles/_global.scss
  src/styles/index.scss
Labels: bug, review, waiting for review

#81 Round numbers
  src/components/BasketList/index.jsx
  src/containers/ConfirmOrder/index.jsx
  src/containers/ProductBasket/index.jsx
  src/containers/ProductPage/index.jsx
  src/containers/Receipt/index.jsx
Labels: bug, review, waiting for review

#80 Keep search
  src/components/Spinner/index.js
  src/containers/ProductSearch/index.jsx
  src/reflux/Actions.js
  src/reflux/OrderStore.js
  src/reflux/ProductStore.js
  src/utils/index.js
Labels: enhancement, review, waiting for review

#83 Code refactoring
  src/components/BasketList/index.jsx
  src/components/DayPickerWrapper/index.jsx
  src/components/DayPickerWrapper/index.scss
  src/components/Footer/index.jsx
  src/components/Header/index.jsx
  src/components/Notification/index.jsx
  src/components/PaymentForm/index.jsx
  src/components/PlaceAutoCompleteWrapper/index.jsx
  src/components/ProductImage/index.jsx
  src/components/ProductList/index.jsx
  src/components/ProductRecommendations/index.jsx
  src/components/ShoppingCart/index.jsx
  src/components/Spinner/index.js
  src/components/SvgIcons/EditIcon.js
  src/components/SvgIcons/ShoppingCartIcon.js
  src/components/SvgIcons/UserIcon.js
  src/components/TimePickerWrapper/index.jsx
  src/containers/ConfirmOrder/index.jsx
  src/containers/DeliveryDetails/index.jsx
  src/containers/PaymentDetails/index.jsx
  src/containers/ProductBasket/index.jsx
  src/containers/ProductBasket/index.scss
  src/containers/ProductPage/index.jsx
  src/containers/ProductSearch/index.jsx
  src/containers/Receipt/index.jsx
  src/containers/UserDetails/index.jsx
Labels: enhancement, review, waiting for review
